version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_SITE_NAME: "ContenidosX"
      # --- Supabase ---
      NEXT_PUBLIC_SUPABASE_URL: "${NEXT_PUBLIC_SUPABASE_URL}"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "${NEXT_PUBLIC_SUPABASE_ANON_KEY}"
      SUPABASE_SERVICE_ROLE_KEY: "${SUPABASE_SERVICE_ROLE_KEY}"
      # --- Stripe ---
      STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}"
      STRIPE_WEBHOOK_SECRET: "${STRIPE_WEBHOOK_SECRET}"
      # --- Emails (opcional) ---
      RESEND_API_KEY: "${RESEND_API_KEY}"
    restart: unless-stopped

  # Webhook forwarder (opcional, para desarrollo local con Stripe CLI)
  # stripe:
  #   image: stripe/stripe-cli
  #   command: listen --forward-to web:3000/api/webhooks/stripe
  #   environment:
  #     STRIPE_API_KEY: "${STRIPE_SECRET_KEY}"
  #   depends_on:
  #     - web
