#!/bin/bash

echo "🚀 CONFIGURANDO GITHUB SECRETS PASO A PASO"
echo "=========================================="
echo ""

# Colores para output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 INSTRUCCIONES PARA CONFIGURAR GITHUB SECRETS${NC}"
echo ""
echo -e "${YELLOW}1. 🔑 OBTENER TOKEN DE FLY.IO:${NC}"
echo "   - Ve a https://fly.io/dashboard"
echo "   - Account → Access Tokens"
echo "   - Create Token → Personal Access Token"
echo "   - Copia el token (fly_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)"
echo ""
echo -e "${YELLOW}2. 🗄️ OBTENER DATABASE_URL:${NC}"
echo "   - Ve a tu proyecto Supabase"
echo "   - Settings → Database"
echo "   - Connection string → URI"
echo "   - Copia la URL (postgresql://...)"
echo ""
echo -e "${YELLOW}3. 💳 OBTENER STRIPE_SECRET_KEY:${NC}"
echo "   - Ve a https://dashboard.stripe.com"
echo "   - Developers → API keys"
echo "   - Copia Secret key (sk_test_***HIDDEN***... o sk_live_...)"
echo ""
echo -e "${YELLOW}4. 🔗 OBTENER STRIPE_WEBHOOK_SECRET:${NC}"
echo "   - Ve a https://dashboard.stripe.com"
echo "   - Developers → Webhooks"
echo "   - Selecciona tu webhook"
echo "   - Copia Signing secret (whsec_...)"
echo ""
echo -e "${YELLOW}5. 🔧 CONFIGURAR EN GITHUB:${NC}"
echo "   - Ve a tu repositorio en GitHub"
echo "   - Settings → Secrets and variables → Actions"
echo "   - New repository secret"
echo "   - Configura estos 5 secrets:"
echo ""
echo -e "${BLUE}   SECRETS A CONFIGURAR:${NC}"
echo "   ┌─────────────────────────────────┬─────────────────────────────────┐"
echo "   │ Nombre del Secret               │ Valor                           │"
echo "   ├─────────────────────────────────┼─────────────────────────────────┤"
echo "   │ FLY_API_TOKEN_STAGING          │ [tu token de Fly.io]            │"
echo "   │ FLY_API_TOKEN_PRODUCTION       │ [tu token de Fly.io]            │"
echo "   │ DATABASE_URL                   │ [tu DATABASE_URL de Supabase]   │"
echo "   │ STRIPE_SECRET_KEY              │ [tu STRIPE_SECRET_KEY]          │"
echo "   │ STRIPE_WEBHOOK_SECRET          │ [tu STRIPE_WEBHOOK_SECRET]      │"
echo "   └─────────────────────────────────┴─────────────────────────────────┘"
echo ""
echo -e "${GREEN}✅ DESPUÉS DE CONFIGURAR:${NC}"
echo "1. Haz push a tu repositorio"
echo "2. Los workflows se ejecutarán automáticamente"
echo "3. Verifica en Actions tab que todo funcione"
echo ""
echo -e "${YELLOW}💡 TIP:${NC}"
echo "Puedes usar el mismo token de Fly.io para staging y producción"
echo ""
echo -e "${GREEN}🚀 ¡CONFIGURA ESTOS SECRETS Y TU CI/CD ESTARÁ LISTO!${NC}"
