name: DB Migrations
on:
  workflow_dispatch:
    inputs:
      file:
        description: 'SQL file to run (e.g., migrations/v11.sql)'
        required: true
        default: 'migrations/v11.sql'
  push:
    branches: [ main ]
    paths:
      - 'migrations/**.sql'

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install psql
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run migration
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          if [ -z "${{ github.event.inputs.file }}" ]; then
            FILE="migrations/v11.sql"
          else
            FILE="${{ github.event.inputs.file }}"
          fi
          echo "Applying $FILE"
          psql "$DATABASE_URL" -v "ON_ERROR_STOP=1" -f "$FILE"
